name: Build/Test checks
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check_linux_build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install make gcc # Add more deps when needed
      - uses: actions/checkout@v4
      - run: DEBUG=0 ASAN=0 ANALYZER=0 LTO=1 make
      # TODO: Export test coverage

  check_linux_test:
    runs-on: ubuntu-latest
    needs: check_linux_build
    steps:
      - run: sudo apt install make gcc libcriterion-dev # Add more deps when needed
      - uses: actions/checkout@v4
      - run: DEBUG=1 ASAN=1 ANALYZER=1 LTO=0 make tests_run
      # TODO: Export test coverage
